name: org.version
run-name: org.version ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'set version for build'
        type: string
        required: true

jobs:
  # ╔═════════════════════════════════════════════════════╗
  # ║               BUILD VERSION {N} IMAGE               ║
  # ╚═════════════════════════════════════════════════════╝
  version:
    runs-on: ubuntu-latest
    steps:
      - name: setup config
        uses: actions/github-script@62c3794a3eb6788d9a2a72b219504732c0c9a298
        with:
          script: |
            const { Buffer } = require('node:buffer');
            const etc = {
              version:"${{ github.event.inputs.version }}",
              semver:{disable:{rolling:true}}
            };
            core.exportVariable('WORKFLOW_BASE64JSON', Buffer.from(JSON.stringify(etc)).toString('base64'));

      - name: build container image
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          wait-for-completion: false
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "release":"false", "readme":"false", "etc":"${{ env.WORKFLOW_BASE64JSON }}" }'